package ru.tinkoff.resistance.errocodes

enum class CommandErrorCode(num: Int) {
    ENTER_TO_STARTED_GAME(0),
    ALREADY_IN_GAME(1),
    FULL_LOBBY(2),
    NOT_HOST_START_GAME(3),
    ALREADY_STARTED(4),
    NOT_ENOUGH_PLAYERS_TO_START(5),
    ADD_PLAYER_IN_NOT_TEAM_STATE(6),
    NOT_LEADER_ADD_PLAYER_TO_TEAM(7),
    ALREADY_IN_TEAM(8),
    VOTE_IN_NOT_VOTE_STATE(9),
    ALREADY_VOTE(10),
    DO_MISSION_IN_NOT_MISSION_STATE(11),
    PLAYER_DONT_DO_MISSION(12),
    ALREADY_DONE_MISSION(13),
    GAME_NOT_FOUND(14),
    PLAYER_NOT_IN_GAME(15),
    LEAVE_FROM_LOBBY_IN_NOT_LOBBY_STATE(16),
}